### ISSUE TITLE
Visualization should support adding non-linearization related events 

### ISSUE THREAD

**Issue by serathius** [anishathalye/porcupine#14]
Porcupine visualization is a great tool to view history of operations done in model. However it only graphs event history outputted from linearization. 

In the real system there might be events that are not directly  part of model of linearization, still they might have a influence of correctness of the system. For example we might want to test database like etcd correctness under different types of disruptions, like process kill. Process kill event is not directly part of linearization, however it would be really useful to be able to show the event in the visualization. 

Would be great to have a method `linearizationInfo.AddEvent(start, end int, name string)`, that allows to additional block that will be showed on the visualization. Additional recommendation would be to make `linearizationInfo` public struct. Having a public function returning private struct is a antipattern in Go. 

As a workaround, it is possible to add this event as no-op operation to model. This however this will have negative impact on performance.

**Comment by anishathalye** [comment]
Sounds useful! Would you be interested in submitting a PR for this?On Jan 21, 2023, at 5:48 AM, Marek Siarkowicz ***@***.***> wrote:﻿
Porcupine visualization is a great tool to view history of operations done in model. However it only graphs event history outputted from linearization.
In the real system there might be events that are not directly  part of model of linearization, still they might have a influence of correctness of the system. For example we might want to test database like etcd correctness under different types of disruptions, like process kill. Process kill event is not directly part of linearization, however it would be really useful to be able to show the event in the visualization.
Would be great to have a method linearizationInfo.AddEvent(start, end int, name string), that allows to additional block that will be showed on the visualization. Additional recommendation would be to make linearizationInfo public struct. Having a public function returning private struct is a antipattern in Go.
As a workaround, it is possible to add this event as no-op operation to model. This however this will have negative impact on performance.
