### ISSUE TITLE
how to check strong consistency of database

### ISSUE THREAD

**Issue by thinhdanggroup** [anishathalye/porcupine#7]
Hi @anishathalye,

Currently, I am using https://github.com/pingcap/chaos to check strong consistency of TiDB. But  **porcupine** don't work with too many events so all my tests are out of memory before my chaos run.

Can you give me any solution to check strong consistency of database with chaos?

Besides, I propose that we can run continuously test ( about 200 events logs per test) and use **porcupine** to check them. If all tests passed, the database would be strong consistency. Is that true?

**Comment by anishathalye** [comment]
Regarding the verifier being slow, see #4.

Also, passing tests does not imply that the database is correct -- it just means that a particular run of the database was correct.

**Comment by anishathalye** [comment]
Going to close this for now. Feel free to re-open if you have any other questions.
