### ISSUE TITLE
if and only if ??

### ISSUE THREAD

**Issue by iwanttobepowerful** [anishathalye/porcupine#9]
https://github.com/anishathalye/porcupine/blob/1c86176831911f0c7a37430bd41a2b2dbb2f1528/model.go#L28

**Comment by anishathalye** [comment]
What is the question?

**Comment by cristaloleg** [comment]
Looks like @iwanttobepowerful is talking about `s/if an only/if and only`

**Comment by anishathalye** [comment]
Thank you, fixed.
